#!/bin/bash

# NeuroClima Configuration Setup Wizard
# This script will help you create the necessary configuration files for deployment

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║        NeuroClima Kubernetes Configuration Wizard          ║${NC}"
echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo ""

# Function to prompt for input
prompt() {
    local var_name=$1
    local prompt_text=$2
    local default_value=$3

    if [ -n "$default_value" ]; then
        read -p "$(echo -e ${GREEN}$prompt_text ${YELLOW}[$default_value]${NC}: )" value
        value=${value:-$default_value}
    else
        read -p "$(echo -e ${GREEN}$prompt_text${NC}: )" value
    fi

    echo "$value"
}

echo -e "${YELLOW}Step 1: External Services Configuration${NC}"
echo "----------------------------------------"

# Get VM IP
VM_IP=$(prompt "VM_IP" "Enter your VM IP address or hostname" "192.168.1.100")

# Get MinIO configuration
echo ""
echo -e "${YELLOW}Step 2: MinIO Configuration${NC}"
echo "----------------------------------------"
MINIO_ACCESS_KEY=$(prompt "MINIO_ACCESS_KEY" "MinIO Access Key" "minioadmin")
MINIO_SECRET_KEY=$(prompt "MINIO_SECRET_KEY" "MinIO Secret Key" "minioadmin")
MINIO_SECURE=$(prompt "MINIO_SECURE" "Use HTTPS for MinIO? (true/false)" "false")

# Get Milvus configuration
echo ""
echo -e "${YELLOW}Step 3: Milvus Configuration${NC}"
echo "----------------------------------------"
MILVUS_USER=$(prompt "MILVUS_USER" "Milvus Username" "root")
MILVUS_PASSWORD=$(prompt "MILVUS_PASSWORD" "Milvus Password" "Milvus")

# Get Redis password
echo ""
echo -e "${YELLOW}Step 4: Redis Configuration${NC}"
echo "----------------------------------------"
REDIS_PASSWORD=$(prompt "REDIS_PASSWORD" "Redis Password" "redis123")

# Get Admin credentials
echo ""
echo -e "${YELLOW}Step 5: Admin Credentials${NC}"
echo "----------------------------------------"
ADMIN_USERNAME=$(prompt "ADMIN_USERNAME" "Admin Username" "admin")
ADMIN_PASSWORD=$(prompt "ADMIN_PASSWORD" "Admin Password" "admin123")

# Generate SECRET_KEY if openssl is available
if command -v openssl &> /dev/null; then
    SECRET_KEY=$(openssl rand -hex 32)
    echo -e "${GREEN}Generated SECRET_KEY${NC}: $SECRET_KEY"
else
    SECRET_KEY="change-this-to-a-random-secret-key-in-production"
    echo -e "${YELLOW}Warning: openssl not found. Using default SECRET_KEY.${NC}"
fi

# Optional services
echo ""
echo -e "${YELLOW}Step 6: Optional Services (press Enter to skip)${NC}"
echo "----------------------------------------"
OPENAI_API_KEY=$(prompt "OPENAI_API_KEY" "OpenAI API Key (optional)" "")
MAILEROO_API_KEY=$(prompt "MAILEROO_API_KEY" "Maileroo API Key (optional)" "")
MAILEROO_FROM_EMAIL=$(prompt "MAILEROO_FROM_EMAIL" "Maileroo From Email (optional)" "")

# Create configmap.yaml
echo ""
echo -e "${BLUE}Creating base/configmap.yaml...${NC}"

cat > base/configmap.yaml << EOF
# NeuroClima Kubernetes ConfigMap
# Auto-generated by setup-config.sh

apiVersion: v1
kind: ConfigMap
metadata:
  name: neuroclima-config
  namespace: uoulu
data:
  # External services
  OLLAMA_API_URL: "http://${VM_IP}:11434"
  OLLAMA_HOST: "${VM_IP}"
  OLLAMA_PORT: "11434"
  MINIO_ENDPOINT: "${VM_IP}:9000"
  MILVUS_HOST: "${VM_IP}"
  MILVUS_PORT: "19530"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-config
  namespace: uoulu
data:
  # Application Settings
  APP_NAME: "NeuroClima Document Processor"
  APP_VERSION: "7.0.0"
  DEBUG: "False"
  LOG_LEVEL: "INFO"
  HOST: "0.0.0.0"
  PORT: "5000"

  # Processing Configuration
  MAX_CONCURRENT_TASKS: "1"
  MODEL_PROVIDER: "free"

  # OpenAI Configuration
  OPENAI_MODEL: "gpt-4o"
  OPENAI_EMBEDDING_MODEL: "text-embedding-3-large"
  OPENAI_TIMEOUT: "2"
  OPENAI_API_BASE: "https://api.openai.com/v1/chat/completions"

  # Ollama Configuration
  OLLAMA_MODEL: "mistral:7b"
  OLLAMA_EMBEDDING_MODEL: "nomic-embed-text"
  OLLAMA_TIMEOUT: "20000"

  # MinIO Configuration
  SECURE: "${MINIO_SECURE}"
  PROCESSABLE_BUCKETS: "researchpapers,policy,news,scientificdata"

  # Milvus Configuration
  MILVUS_USER: "${MILVUS_USER}"
  MILVUS_PASSWORD: "${MILVUS_PASSWORD}"
  MILVUS_CHUNK_DATABASE: "chunk_prod"
  MILVUS_SUMMARY_DATABASE: "summary_prod"
  MILVUS_COLLECTION_NEWS: "News"
  MILVUS_COLLECTION_SCIENTIFICDATA: "Scientific_Data"
  MILVUS_COLLECTION_POLICY: "Policy"
  MILVUS_COLLECTION_RESEARCHPAPERS: "Research_Papers"

  # Document Processing
  UNSTRUCTURED_API_URL: "http://neuroclima-unstructured:8000"
  CHUNK_SIZE: "1000"
  CHUNK_OVERLAP: "200"

  # GraphRAG Configuration
  GRAPHRAG_ENABLED: "true"
  GRAPHRAG_STORAGE_ROOT: "/app/data/graphrag"
  GRAPHRAG_QUERY_CHAT_MODEL_API_BASE: "http://${VM_IP}:11434/v1"
  GRAPHRAG_QUERY_EMBEDDING_MODEL_API_BASE: "http://${VM_IP}:11434/api"
  GRAPHRAG_INDEXING_CHAT_MODEL_API_BASE: "http://${VM_IP}:11434/v1"
  GRAPHRAG_EMBEDDING_MODEL_API_BASE: "http://${VM_IP}:11434/api"

  # LanceDB Configuration
  LANCEDB_ENABLED: "true"
  LANCEDB_PATH: "/app/data/lancedb"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: uoulu
data:
  # Application Settings
  DEBUG: "true"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  ENVIRONMENT: "development"
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "1"
  RELOAD: "false"

  # MinIO Configuration
  MINIO_SECURE: "${MINIO_SECURE}"
  MINIO_REGION: "us-east-1"
  MINIO_TIMEOUT: "10"
  MINIO_BUCKET_NEWS: "news"
  MINIO_BUCKET_POLICY: "policies"
  MINIO_BUCKET_RESEARCH_PAPERS: "researchpapers"
  MINIO_BUCKET_SCIENTIFIC_DATA: "scientificdata"
  MINIO_BUCKET_REPORTS: "reports"
  MINIO_DEFAULT_BUCKET: "researchpapers"

  # Database Configuration
  DATABASE_URL: "sqlite:////app/data/neuroclima.db"
  DATABASE_ECHO: "false"

  # Redis Configuration
  REDIS_HOST: "neuroclima-redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_DECODE_RESPONSES: "true"

  # Session Configuration
  SESSION_TIMEOUT: "3600"
  SESSION_COOKIE_SECURE: "false"
  SESSION_COOKIE_HTTPONLY: "true"
  SESSION_COOKIE_SAMESITE: "lax"

  # CORS Configuration
  CORS_ORIGINS: '["http://localhost:3000","http://localhost:5173","http://localhost:8080"]'
  CORS_CREDENTIALS: "true"
  CORS_METHODS: '["GET","POST","PUT","DELETE","OPTIONS","PATCH"]'
  CORS_HEADERS: '["*"]'

  # Document Processing
  PROCESSOR_URL: "http://neuroclima-processor:5000"
EOF

echo -e "${GREEN}✓ Created base/configmap.yaml${NC}"

# Create secrets-ready.yaml
echo -e "${BLUE}Creating base/secrets-ready.yaml...${NC}"

cat > base/secrets-ready.yaml << EOF
# NeuroClima Kubernetes Secrets
# Auto-generated by setup-config.sh
# WARNING: Keep this file secure and do not commit to version control!

apiVersion: v1
kind: Secret
metadata:
  name: neuroclima-secrets
  namespace: uoulu
type: Opaque
stringData:
  # MinIO credentials
  MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"

  # Milvus credentials
  MILVUS_USER: "${MILVUS_USER}"
  MILVUS_PASSWORD: "${MILVUS_PASSWORD}"

  # Redis password
  REDIS_PASSWORD: "${REDIS_PASSWORD}"

  # OpenAI API key (optional)
  OPENAI_API_KEY: "${OPENAI_API_KEY}"

  # Server secret key for JWT and session management
  SECRET_KEY: "${SECRET_KEY}"

  # Admin credentials
  ADMIN_USERNAME: "${ADMIN_USERNAME}"
  ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

  # Email credentials - Maileroo
  MAILEROO_API_KEY: "${MAILEROO_API_KEY}"
  MAILEROO_FROM_EMAIL: "${MAILEROO_FROM_EMAIL}"

  # Email credentials - SMTP (fallback)
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""

  # Langfuse credentials (observability/tracing)
  LANGFUSE_SECRET_KEY: ""
  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_HOST: ""
EOF

echo -e "${GREEN}✓ Created base/secrets-ready.yaml${NC}"

echo ""
echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║              Configuration Complete!                       ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Configuration summary:${NC}"
echo "  VM IP/Hostname: ${VM_IP}"
echo "  Ollama URL: http://${VM_IP}:11434"
echo "  MinIO Endpoint: ${VM_IP}:9000"
echo "  Milvus Host: ${VM_IP}"
echo "  MinIO Secure: ${MINIO_SECURE}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Review the generated files:"
echo "     - base/configmap.yaml"
echo "     - base/secrets-ready.yaml"
echo ""
echo "  2. Deploy to Kubernetes:"
echo "     ${GREEN}./quick-deploy.sh${NC}"
echo ""
echo -e "${YELLOW}Note: Make sure your Kubernetes cluster can reach ${VM_IP}${NC}"
