# NeuroClima Configuration Setup Wizard (PowerShell)
# This script will help you create the necessary configuration files for deployment

# Color functions
function Write-Header {
    param([string]$Message)
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host $Message -ForegroundColor Cyan
    Write-Host "============================================================" -ForegroundColor Cyan
}

function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Green
}

function Write-Step {
    param([string]$Message)
    Write-Host "`n$Message" -ForegroundColor Yellow
    Write-Host "----------------------------------------" -ForegroundColor Yellow
}

function Get-UserInput {
    param(
        [string]$Prompt,
        [string]$Default = ""
    )

    if ($Default) {
        $input = Read-Host "$Prompt [$Default]"
        if ([string]::IsNullOrWhiteSpace($input)) {
            return $Default
        }
        return $input
    } else {
        return Read-Host $Prompt
    }
}

Clear-Host
Write-Header "NeuroClima Kubernetes Configuration Wizard"
Write-Host ""

# Step 1: External Services
Write-Step "Step 1: External Services Configuration"
$VM_IP = Get-UserInput -Prompt "Enter your VM IP address or hostname" -Default "192.168.1.100"

# Step 2: MinIO Configuration
Write-Step "Step 2: MinIO Configuration"
$MINIO_ACCESS_KEY = Get-UserInput -Prompt "MinIO Access Key" -Default "minioadmin"
$MINIO_SECRET_KEY = Get-UserInput -Prompt "MinIO Secret Key" -Default "minioadmin"
$MINIO_SECURE = Get-UserInput -Prompt "Use HTTPS for MinIO? (true/false)" -Default "false"

# Step 3: Milvus Configuration
Write-Step "Step 3: Milvus Configuration"
$MILVUS_USER = Get-UserInput -Prompt "Milvus Username" -Default "root"
$MILVUS_PASSWORD = Get-UserInput -Prompt "Milvus Password" -Default "Milvus"

# Step 4: Redis Configuration
Write-Step "Step 4: Redis Configuration"
$REDIS_PASSWORD = Get-UserInput -Prompt "Redis Password" -Default "redis123"

# Step 5: Admin Credentials
Write-Step "Step 5: Admin Credentials"
$ADMIN_USERNAME = Get-UserInput -Prompt "Admin Username" -Default "admin"
$ADMIN_PASSWORD = Get-UserInput -Prompt "Admin Password" -Default "admin123"

# Generate SECRET_KEY
$SECRET_KEY = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 64 | ForEach-Object {[char]$_})
Write-Info "Generated SECRET_KEY: $SECRET_KEY"

# Step 6: Optional Services
Write-Step "Step 6: Optional Services (press Enter to skip)"
$OPENAI_API_KEY = Get-UserInput -Prompt "OpenAI API Key (optional)" -Default ""
$MAILEROO_API_KEY = Get-UserInput -Prompt "Maileroo API Key (optional)" -Default ""
$MAILEROO_FROM_EMAIL = Get-UserInput -Prompt "Maileroo From Email (optional)" -Default ""

# Create configmap.yaml
Write-Host ""
Write-Info "Creating base/configmap.yaml..."

$configMapContent = @"
# NeuroClima Kubernetes ConfigMap
# Auto-generated by Setup-Config.ps1

apiVersion: v1
kind: ConfigMap
metadata:
  name: neuroclima-config
  namespace: uoulu
data:
  # External services
  OLLAMA_API_URL: "http://${VM_IP}:11434"
  OLLAMA_HOST: "${VM_IP}"
  OLLAMA_PORT: "11434"
  MINIO_ENDPOINT: "${VM_IP}:9000"
  MILVUS_HOST: "${VM_IP}"
  MILVUS_PORT: "19530"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-config
  namespace: uoulu
data:
  # Application Settings
  APP_NAME: "NeuroClima Document Processor"
  APP_VERSION: "7.0.0"
  DEBUG: "False"
  LOG_LEVEL: "INFO"
  HOST: "0.0.0.0"
  PORT: "5000"

  # Processing Configuration
  MAX_CONCURRENT_TASKS: "1"
  MODEL_PROVIDER: "free"

  # OpenAI Configuration
  OPENAI_MODEL: "gpt-4o"
  OPENAI_EMBEDDING_MODEL: "text-embedding-3-large"
  OPENAI_TIMEOUT: "2"
  OPENAI_API_BASE: "https://api.openai.com/v1/chat/completions"

  # Ollama Configuration
  OLLAMA_MODEL: "mistral:7b"
  OLLAMA_EMBEDDING_MODEL: "nomic-embed-text"
  OLLAMA_TIMEOUT: "20000"

  # MinIO Configuration
  SECURE: "${MINIO_SECURE}"
  PROCESSABLE_BUCKETS: "researchpapers,policy,news,scientificdata"

  # Milvus Configuration
  MILVUS_USER: "${MILVUS_USER}"
  MILVUS_PASSWORD: "${MILVUS_PASSWORD}"
  MILVUS_CHUNK_DATABASE: "chunk_prod"
  MILVUS_SUMMARY_DATABASE: "summary_prod"
  MILVUS_COLLECTION_NEWS: "News"
  MILVUS_COLLECTION_SCIENTIFICDATA: "Scientific_Data"
  MILVUS_COLLECTION_POLICY: "Policy"
  MILVUS_COLLECTION_RESEARCHPAPERS: "Research_Papers"

  # Document Processing
  UNSTRUCTURED_API_URL: "http://neuroclima-unstructured:8000"
  CHUNK_SIZE: "1000"
  CHUNK_OVERLAP: "200"

  # GraphRAG Configuration
  GRAPHRAG_ENABLED: "true"
  GRAPHRAG_STORAGE_ROOT: "/app/data/graphrag"
  GRAPHRAG_QUERY_CHAT_MODEL_API_BASE: "http://${VM_IP}:11434/v1"
  GRAPHRAG_QUERY_EMBEDDING_MODEL_API_BASE: "http://${VM_IP}:11434/api"
  GRAPHRAG_INDEXING_CHAT_MODEL_API_BASE: "http://${VM_IP}:11434/v1"
  GRAPHRAG_EMBEDDING_MODEL_API_BASE: "http://${VM_IP}:11434/api"

  # LanceDB Configuration
  LANCEDB_ENABLED: "true"
  LANCEDB_PATH: "/app/data/lancedb"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: uoulu
data:
  # Application Settings
  DEBUG: "true"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  ENVIRONMENT: "development"
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "1"
  RELOAD: "false"

  # MinIO Configuration
  MINIO_SECURE: "${MINIO_SECURE}"
  MINIO_REGION: "us-east-1"
  MINIO_TIMEOUT: "10"
  MINIO_BUCKET_NEWS: "news"
  MINIO_BUCKET_POLICY: "policies"
  MINIO_BUCKET_RESEARCH_PAPERS: "researchpapers"
  MINIO_BUCKET_SCIENTIFIC_DATA: "scientificdata"
  MINIO_BUCKET_REPORTS: "reports"
  MINIO_DEFAULT_BUCKET: "researchpapers"

  # Database Configuration
  DATABASE_URL: "sqlite:////app/data/neuroclima.db"
  DATABASE_ECHO: "false"

  # Redis Configuration
  REDIS_HOST: "neuroclima-redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_DECODE_RESPONSES: "true"

  # Session Configuration
  SESSION_TIMEOUT: "3600"
  SESSION_COOKIE_SECURE: "false"
  SESSION_COOKIE_HTTPONLY: "true"
  SESSION_COOKIE_SAMESITE: "lax"

  # CORS Configuration
  CORS_ORIGINS: '["http://localhost:3000","http://localhost:5173","http://localhost:8080"]'
  CORS_CREDENTIALS: "true"
  CORS_METHODS: '["GET","POST","PUT","DELETE","OPTIONS","PATCH"]'
  CORS_HEADERS: '["*"]'

  # Document Processing
  PROCESSOR_URL: "http://neuroclima-processor:5000"
"@

$configMapContent | Out-File -FilePath "base/configmap.yaml" -Encoding UTF8
Write-Info "✓ Created base/configmap.yaml"

# Create secrets-ready.yaml
Write-Info "Creating base/secrets-ready.yaml..."

$secretsContent = @"
# NeuroClima Kubernetes Secrets
# Auto-generated by Setup-Config.ps1
# WARNING: Keep this file secure and do not commit to version control!

apiVersion: v1
kind: Secret
metadata:
  name: neuroclima-secrets
  namespace: uoulu
type: Opaque
stringData:
  # MinIO credentials
  MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"

  # Milvus credentials
  MILVUS_USER: "${MILVUS_USER}"
  MILVUS_PASSWORD: "${MILVUS_PASSWORD}"

  # Redis password
  REDIS_PASSWORD: "${REDIS_PASSWORD}"

  # OpenAI API key (optional)
  OPENAI_API_KEY: "${OPENAI_API_KEY}"

  # Server secret key for JWT and session management
  SECRET_KEY: "${SECRET_KEY}"

  # Admin credentials
  ADMIN_USERNAME: "${ADMIN_USERNAME}"
  ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

  # Email credentials - Maileroo
  MAILEROO_API_KEY: "${MAILEROO_API_KEY}"
  MAILEROO_FROM_EMAIL: "${MAILEROO_FROM_EMAIL}"

  # Email credentials - SMTP (fallback)
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""

  # Langfuse credentials (observability/tracing)
  LANGFUSE_SECRET_KEY: ""
  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_HOST: ""
"@

$secretsContent | Out-File -FilePath "base/secrets-ready.yaml" -Encoding UTF8
Write-Info "✓ Created base/secrets-ready.yaml"

Write-Host ""
Write-Header "Configuration Complete!"
Write-Host ""
Write-Host "Configuration summary:" -ForegroundColor Green
Write-Host "  VM IP/Hostname: $VM_IP"
Write-Host "  Ollama URL: http://${VM_IP}:11434"
Write-Host "  MinIO Endpoint: ${VM_IP}:9000"
Write-Host "  Milvus Host: ${VM_IP}"
Write-Host "  MinIO Secure: ${MINIO_SECURE}"
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Review the generated files:"
Write-Host "     - base/configmap.yaml"
Write-Host "     - base/secrets-ready.yaml"
Write-Host ""
Write-Host "  2. Deploy to Kubernetes:"
Write-Host "     " -NoNewline
Write-Host ".\deploy-k8s.ps1 -Action all" -ForegroundColor Green
Write-Host ""
Write-Host "Note: Make sure your Kubernetes cluster can reach $VM_IP" -ForegroundColor Yellow
